version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=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
      - SUPABASE_URL=https://fgvyotgowmcwcphsctlc.supabase.co
    depends_on:
      - redis
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped
    networks:
      - app-network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -c "from app.services.worker import run_worker; run_worker()"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=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
      - SUPABASE_URL=https://fgvyotgowmcwcphsctlc.supabase.co
    depends_on:
      - redis
      - api
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

  # Local database for development (use Supabase in production)
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cre8rflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - local  # Only start with docker-compose --profile local up

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
    driver: bridge 